site_name: OE Logic Guide
site_url: https://space-cee.github.io/oe-logic-guide/
theme:
  name: material
  features:
    - navigation.expand      # collapsible categories in sidebar
    - navigation.instant     # sidebar highlights current page
    - search.highlight
    - search.suggest
    - toc.integrate          # integrate table of contents into sidebar

nav:
  - Home: index.md
  - OE Logic:
      - Communication:
          - Placeholder: OE LOGIC/COMMUNICATION/Placeholder.md
      - Converter:
          - Byte: OE LOGIC/CONVERTER/Byte.md
          - Color: OE LOGIC/CONVERTER/Color.md
          - Units: OE LOGIC/CONVERTER/Units.md
          - Vectors:
              - Vector Cross Product: OE LOGIC/CONVERTER/VECTORS/VectorCrossProduct.md
      - Display:
          - Lamps: OE LOGIC/DISPLAY/Lamps.md
      - Gates:
          - AND: OE LOGIC/GATES/AND.md
      - Math:
          - ABS: OE LOGIC/MATH/ABS.md
          - Byte: OE LOGIC/MATH/Byte.md
          - Trigonometry: OE LOGIC/MATH/Trigonometry.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/space-cee/oe-logic-guide
