site_name: OE Logic Guide
site_url: https://space-cee.github.io/oe-logic-guide/
theme:
  name: material
  features:
    - navigation.expand      # collapsible categories in sidebar
    - navigation.instant     # sidebar highlights current page
    - search.highlight
    - search.suggest
    - toc.integrate          # integrate table of contents into sidebar

nav:
  - Home: index.md
  - OE Logic:
      - Math:
          - ABS: OE LOGIC/MATH/ABS.md
          # Add more Math blocks here
      - Gates:
          - AND: OE LOGIC/GATES/AND.md
          # Add more Gates blocks here
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/space-cee/oe-logic-guide
