site_name: OE Logic Guide
site_url: https://space-cee.github.io/oe-logic-guide/
theme:
  name: material
  features:
    - navigation.expand      # collapsible categories in sidebar
    - navigation.instant     # sidebar highlights current page
    - search.highlight
    - search.suggest
    - toc.integrate          # integrate table of contents into sidebar

nav:
  - Home: index.md
  - OE Logic:
        - Communication:
        - Converter:
          - Byte:
          - Color:
          - Units:
          - Vector:
        - Display:
          - Lamps:
        - Gates:
          - AND:
          # Add more Gates blocks here
        - GUI:
        - Math:
          - ABS: OE LOGIC/MATH/ABS.md
          # Add more Math blocks here
          - Byte:
          - Trigonometry:
        - Memory:
        - Other:
        - Particle:
        - Sensor:
        - Sound:
        - String:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/space-cee/oe-logic-guide
